### ISSUE TITLE
Provide a download for Linux

### ISSUE THREAD

**Issue by probonopd** [qtplatz/qtplatz#3]
Currently there is no download of Qt-Platz available for Linux, at least I could not find one. This makes it unnecessarily hard to run Qt-Platz on Linux. Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed (unlike Snap and Flatpak)
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs (unlike Flatpak)
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

The [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) tool greatly simplifies creating an AppImage. Let me know if you would like to have some help.

**Comment by qtplatz** [comment]
Thank you for your comments.  QtPlatz is mainly developing on Debian Linux so that is quite easy to build a package (.deb) via cpack already contained in QtPlatz's cmake build system.  I have no experience on AppImage though I'll think about it in future.

**Comment by probonopd** [comment]
Please check out https://obs-ai and https://github.com/probonopd/linuxdeployqt#using-linuxdeployqt-with-travis-ci - doing continuous builds on one of those services is easier than you might think.
